# Generated by Django 2.2.2 on 2019-06-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='validation',
            field=models.CharField(blank=True, max_length=32, verbose_name='code'),
        ),
    ]
