version: "3"
services:
  backend:
    image: motion_django:latest
    command: "sh /backend/scripts/run_dev.sh"
    ports:
      - "8000:8000"
      - "2222:22"
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend
      - static-files:/static-files/

  postgres:
    image: postgres:latest
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
  motion_django:
  static-files:
  media-files:
